name = "talc"
version = "0.1.0"
description = "npm packaging tool for Gleam libraries"
licences = ["MIT"]
repository = { type = "github", user = "tylerbutler", repo = "talc" }
gleam = ">= 1.7.0"

internal_modules = [
  "talc/internal",
  "talc/internal/*",
]

[dependencies]
gleam_stdlib = ">= 0.70.0 and < 1.0.0"
tom = ">= 2.0.0 and < 3.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
glint = ">= 1.2.0 and < 2.0.0"
argv = ">= 1.0.0 and < 2.0.0"
gleam_package_interface = ">= 3.0.1 and < 4.0.0"
ccl = { git = "https://github.com/tylerbutler/ccl_gleam.git", ref = "main" }

[dev-dependencies]
startest = ">= 0.8.0 and < 1.0.0"
